// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// MakeSureTextboxEmpty - Use 'MakeSureTextboxEmptyParams' to pass parameters into this method.
        /// </summary>
        public void MakeSureTextboxEmpty()
        {
            #region Variable Declarations
            WinWindow uIMenuStrip1Window = this.UISpreadsheetuntitledWindow.UISpreadsheetuntitledClient.UIMenuStrip1Window;
            WinEdit uICellContentTextBoxEdit = this.UISpreadsheetuntitledWindow.UICellContentTextBoxWindow.UICellContentTextBoxEdit;
            #endregion

            // Click 'menuStrip1' window
            Mouse.Click(uIMenuStrip1Window, new Point(450, 55));

            // Type '=1+1' in 'cellContentTextBox' text box
            uICellContentTextBoxEdit.Text = this.MakeSureTextboxEmptyParams.UICellContentTextBoxEditText;

            // Type '{Enter}' in 'cellContentTextBox' text box
            Keyboard.SendKeys(uICellContentTextBoxEdit, this.MakeSureTextboxEmptyParams.UICellContentTextBoxEditSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual MakeSureTextboxEmptyParams MakeSureTextboxEmptyParams
        {
            get
            {
                if ((this.mMakeSureTextboxEmptyParams == null))
                {
                    this.mMakeSureTextboxEmptyParams = new MakeSureTextboxEmptyParams();
                }
                return this.mMakeSureTextboxEmptyParams;
            }
        }
        
        public UISpreadsheetuntitledWindow UISpreadsheetuntitledWindow
        {
            get
            {
                if ((this.mUISpreadsheetuntitledWindow == null))
                {
                    this.mUISpreadsheetuntitledWindow = new UISpreadsheetuntitledWindow();
                }
                return this.mUISpreadsheetuntitledWindow;
            }
        }
        #endregion
        
        #region Fields
        private MakeSureTextboxEmptyParams mMakeSureTextboxEmptyParams;
        
        private UISpreadsheetuntitledWindow mUISpreadsheetuntitledWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'MakeSureTextboxEmpty'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class MakeSureTextboxEmptyParams
    {
        
        #region Fields
        /// <summary>
        /// Type '=1+1' in 'cellContentTextBox' text box
        /// </summary>
        public string UICellContentTextBoxEditText = "=1+1";
        
        /// <summary>
        /// Type '{Enter}' in 'cellContentTextBox' text box
        /// </summary>
        public string UICellContentTextBoxEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpreadsheetuntitledWindow : WinWindow
    {
        
        public UISpreadsheetuntitledWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Spreadsheet - untitled";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Spreadsheet - untitled");
            #endregion
        }
        
        #region Properties
        public UISpreadsheetuntitledClient UISpreadsheetuntitledClient
        {
            get
            {
                if ((this.mUISpreadsheetuntitledClient == null))
                {
                    this.mUISpreadsheetuntitledClient = new UISpreadsheetuntitledClient(this);
                }
                return this.mUISpreadsheetuntitledClient;
            }
        }
        
        public UICellContentTextBoxWindow UICellContentTextBoxWindow
        {
            get
            {
                if ((this.mUICellContentTextBoxWindow == null))
                {
                    this.mUICellContentTextBoxWindow = new UICellContentTextBoxWindow(this);
                }
                return this.mUICellContentTextBoxWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISpreadsheetuntitledClient mUISpreadsheetuntitledClient;
        
        private UICellContentTextBoxWindow mUICellContentTextBoxWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpreadsheetuntitledClient : WinClient
    {
        
        public UISpreadsheetuntitledClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Spreadsheet - untitled";
            this.WindowTitles.Add("Spreadsheet - untitled");
            #endregion
        }
        
        #region Properties
        public WinWindow UIMenuStrip1Window
        {
            get
            {
                if ((this.mUIMenuStrip1Window == null))
                {
                    this.mUIMenuStrip1Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIMenuStrip1Window.SearchProperties[WinWindow.PropertyNames.Name] = "menuStrip1";
                    this.mUIMenuStrip1Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
                    this.mUIMenuStrip1Window.WindowTitles.Add("Spreadsheet - untitled");
                    #endregion
                }
                return this.mUIMenuStrip1Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIMenuStrip1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICellContentTextBoxWindow : WinWindow
    {
        
        public UICellContentTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cellContentTextBox";
            this.WindowTitles.Add("Spreadsheet - untitled");
            #endregion
        }
        
        #region Properties
        public WinEdit UICellContentTextBoxEdit
        {
            get
            {
                if ((this.mUICellContentTextBoxEdit == null))
                {
                    this.mUICellContentTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICellContentTextBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Cell Value: ";
                    this.mUICellContentTextBoxEdit.WindowTitles.Add("Spreadsheet - untitled");
                    #endregion
                }
                return this.mUICellContentTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICellContentTextBoxEdit;
        #endregion
    }
}
